condition_images ={
    "Sunny": "pixelArt/conditions/Sunny.bmp",
    "Partly cloudy": "pixelArt/conditions/Partly_cloudy.bmp",
    "Cloudy": "pixelArt/conditions/Cloudy.bmp",
    "Overcast": "pixelArt/conditions/Partly_cloudy.bmp",
    "Mist": "pixelArt/conditions/Cloudy.bmp",
    "Patchy rain possible": "pixelArt/conditions/rain.bmp",
    "Patchy snow possible": "pixelArt/conditions/rain.bmp",
    "Patchy sleet possible": "pixelArt/conditions/rain.bmp",
    "Patchy freezing drizzle possible": "pixelArt/conditions/rain.bmp",
    "Thundery outbreaks possible": "pixelArt/conditions/thunber.bmp",
    "Blowing snow": "pixelArt/conditions/snow.bmp",
    "Blizzard": "pixelArt/conditions/rain.bmp",
    "Fog": "pixelArt/conditions/Cloudy.bmp",
    "Freezing fog": "pixelArt/conditions/Cloudy.bmp",
    "Patchy light drizzle": "pixelArt/conditions/rain.bmp",
    "Light drizzle": "pixelArt/conditions/rain.bmp",
    "Freezing drizzle": "pixelArt/conditions/rain.bmp",
    "Heavy freezing drizzle": "pixelArt/conditions/rain.bmp",
    "Patchy light rain": "pixelArt/conditions/rain.bmp",
    "Light rain": "pixelArt/conditions/rain.bmp",
    "Moderate rain at times": "pixelArt/conditions/rain.bmp",
    "Moderate rain": "pixelArt/conditions/rain.bmp",
    "Heavy rain at times": "pixelArt/conditions/rain.bmp",
    "Heavy rain": "pixelArt/conditions/rain.bmp",
    "Light freezing rain": "pixelArt/conditions/rain.bmp",
    "Moderate or heavy freezing rain": "pixelArt/conditions/rain.bmp",
    "Light sleet": "pixelArt/conditions/rain.bmp",
    "Moderate or heavy sleet": "pixelArt/conditions/rain.bmp",
    "Patchy light snow": "pixelArt/conditions/rain.bmp",
    "Light snow": "pixelArt/conditions/snow.bmp",
    "Patchy moderate snow": "pixelArt/conditions/snow.bmp",
    "Moderate snow": "pixelArt/conditions/snow.bmp",
    "Patchy heavy snow": "pixelArt/conditions/snow.bmp",
    "Heavy snow": "pixelArt/conditions/snow.bmp",
    "Ice pellets": "pixelArt/conditions/snow.bmp",
    "Light rain shower": "pixelArt/conditions/rain.bmp",
    "Moderate or heavy rain shower": "pixelArt/conditions/rain.bmp",
    "Torrential rain shower": "pixelArt/conditions/rain.bmp",
    "Light sleet showers": "pixelArt/conditions/rain.bmp",
    "Moderate or heavy sleet showers": "pixelArt/conditions/rain.bmp",
    "Light snow showers": "pixelArt/conditions/snow.bmp",
    "Moderate or heavy snow showers": "pixelArt/conditions/snow.bmp",
    "Light showers of ice pellets": "pixelArt/conditions/snow.bmp",
    "Moderate or heavy showers of ice pellets": "pixelArt/conditions/snow.bmp",
    "Patchy light rain with thunder": "pixelArt/conditions/thunber.bmp",
    "Moderate or heavy rain with thunder": "pixelArt/conditions/thunber.bmp",
    "Patchy light snow with thunder": "pixelArt/conditions/thunber.bmp",
    "Moderate or heavy snow with thunder": "pixelArt/conditions/thunber.bmp",
}
